### ISSUE TITLE
tensors used as indices must be long or byte tensors

### ISSUE THREAD

**Issue by DreamvLee** [Natsu6767/InfoGAN-PyTorch#1]
I know it looks like a simple problem, but I reported this error in line 108 of the document train.py. The solution on the network is to set index to long or Byte tensor. so I try to convert idx from numpy to tensor and set it to device. ` idx = torch.from_numpy(idx).long().to(device)But` the mistake still happened. Then I found it at https://swift.ctolib.com/article/comments/96546 when np.array is assuming int32 for the indexes, but torch wants int64. I tried this method, but the problem still arose.

**Comment by Natsu6767** [comment]
I am sorry but I don't understand the problem you are facing. What do you mean by solution on the network?
