### ISSUE TITLE
checkpoint/model_epoch_25_MNIST

### ISSUE THREAD

**Issue by AvLab-CV** [Natsu6767/InfoGAN-PyTorch#4]
how to run this ((After training the network to experiment with the latent code for the `MNIST` dataset run **`mnist_generate.py`**:
```sh
python3 mnist_generate.py --load_path /path/to/pth/checkpoint))

**Comment by Natsu6767** [comment]
Provide the path to the checkpoint file that was created during training to the `--load_path` argument.
