### ISSUE TITLE
MNIST results

### ISSUE THREAD

**Issue by hklchung** [Natsu6767/InfoGAN-PyTorch#5]
Hi I am currently also doing an implementation of InfoGAN and one strange bit I have observed that seems to be common across both my own and your results is that the outcome does not appear exactly as expected.

Specifically in my generated outputs, I attempted to force the ordering of numbers to go from 0 to 9 with all 0s at the top row and 9s at the bottom row, in that order. However I seem to be getting different sets of numbers with my control vector and it is consistent and systematic.

I notice your generated outputs also do not follow the sequential order, is that because your results are randomly generated per row or are you also experiencing the same technical errors?

**Comment by Natsu6767** [comment]
It is not guaranteed that the latent space will follow the numerical order every time. There is no information provided while training regarding the order we humans associate with numbers. To the model, the different numbers are simply independent entities. It is just a lucky coincidence to have the generated outputs be in the numerical order.
